
version: '3.8'

services:
  # Development services for each app
  account-dev:
    build:
      context: ./account
      dockerfile: ../Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./account:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5173
    command: npm run dev

  affiliate-dev:
    build:
      context: ./Affiliat
      dockerfile: ../Dockerfile.dev
    ports:
      - "5174:5174"
    volumes:
      - ./Affiliat:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5174
    command: npm run dev

  dashboard-dev:
    build:
      context: ./dashboard
      dockerfile: ../Dockerfile.dev
    ports:
      - "5175:5175"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5175
    command: npm run dev

  address-dev:
    build:
      context: ./address
      dockerfile: ../Dockerfile.dev
    ports:
      - "5176:5176"
    volumes:
      - ./address:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5176
    command: npm run dev

  gst-dev:
    build:
      context: ./set-gst-number
      dockerfile: ../Dockerfile.dev
    ports:
      - "5177:5177"
    volumes:
      - ./set-gst-number:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5177
    command: npm run dev

  refund-dev:
    build:
      context: ./set-refund
      dockerfile: ../Dockerfile.dev
    ports:
      - "5178:5178"
    volumes:
      - ./set-refund:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5178
    command: npm run dev

  wishlist-dev:
    build:
      context: ./wishlist
      dockerfile: ../Dockerfile.dev
    ports:
      - "5179:5179"
    volumes:
      - ./wishlist:/app
      - /app/node_modules
    environment:
      - VITE_PORT=5179
    command: npm run dev

  # Production nginx proxy
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - account-dev
      - affiliate-dev
      - dashboard-dev
      - address-dev
      - gst-dev
      - refund-dev
      - wishlist-dev

networks:
  default:
    name: multi-app-network
